### ISSUE TITLE
询问一下 MacOS 10.15.4 可以使用吗

### ISSUE THREAD

**Issue by Harry-zklcdc** [CrazyPegasus/ThinkPad-T580-Hackintosh#2]
想升级到 10.15.4，想问问这个 EFI 可以使用吗

**Comment by lopsandrea** [comment]
it works perfectly for me except for HDMI

**Comment by Harry-zklcdc** [comment]
> it works perfectly for me except for HDMI

10.15.4？And I can use HDMI in 10.15.3

**Comment by Harry-zklcdc** [comment]
可以使用，我升级到了 10.15.5 了

It can work, and I upgrade to macOS 10.15.5
