### ISSUE TITLE
HDMI doesn't work with OC's big sur setup

### ISSUE THREAD

**Issue by lopsandrea** [CrazyPegasus/ThinkPad-T580-Hackintosh#7]
I tried to fix the problem by following the readme and entering the kext, but it doesn't work. Ideas on how to fix it?

**Comment by CrazyPegasus** [comment]
HDMI output under Big Sur has been tested, the result:
Use MacBookPro14,1 perfect
MacBookPro14,2 perfect
MacBookPro15,2 is perfect, can simultaneously HDMI, type-c
MacBookPro15,4 type-c output is normal, HDMI is normal, not at the same time
MacBookPro16,2 type-c output is normal, HDMI is normal, not at the same time
MacBookPro16,3 type-c output is normal, HDMI is normal, not at the same time
Other models such as MacBook Air8,1 and 8,2 and 9,1 are not tested, if you are interested in testing it yourself
Coincidentally, the models sent to the Git warehouse happened to use MacBookPro14,3; MacBookPro15,1; MacBookPro15,3; MacBookPro16,1; MacBookPro16,4.

**Comment by lopsandrea** [comment]
Thanks a lot it works!
